### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by behnam-lum** [mateusfccp/update_available#3]
I'm not able to add this to my project!
Here is the error message I'm getting:
```
Running "flutter pub get" in hero...                                1.0s
Invalid plugin specification update_available_ios.
Invalid "ios" plugin specification.
exit code 1
```

**Comment by mateusfccp** [comment]
@behnam-lum Thanks for reporting. It was probably introduced in the last release. Working on it.

**Comment by mateusfccp** [comment]
@behnam-lum I published a new version for `update_available_ios`. Could you please clean your dependency caches and try again? `update_available_ios` may be in `1.0.1+1c`.

**Comment by blazeu** [comment]
Now the error is 

```
    [!] No podspec found for `update_available` in `.symlinks/plugins/update_available/ios`
```

I'm using 

```
  update_available: ^1.0.0+1c
  update_available_ios: ^1.0.1+1d
```

Which is the latest version, `1.0.1+1c` still does not work.

**Comment by mateusfccp** [comment]
As there was no other response, I closed the issue.

If you think the issue was not really solved, tell me and I will reopen.
